#!/bin/bash

export M3_HOME=/opt/maven_default
export M3=$M3_HOME/bin
export PATH=$M3:$PATH
export JAVA_HOME=/opt/jdk_default
export PATH=$JAVA_HOME/bin:$PATH
export MAVEN_OPTS="-Xms256m -Xmx512m"

## lrwxrwxrwx 1 build build   20 Mar  8 11:57 src -> zPermissions/src/
## lrwxrwxrwx 1 build build   23 Feb 18 16:39 pom.xml -> zPermissions/pom.xml

rm -rf zPermissions
rm -rf target

git clone https://github.com/mirolm/zPermissions.git

wget http://maven.sk89q.com/repo/org/bukkit/bukkit/1.6.2-R0.1-SNAPSHOT/bukkit-1.6.2-R0.1-20130804.014923-14.jar -O bukkit-1.6.2-R0.1-20130804.014923-14.jar

mvn install:install-file -Dfile=bukkit-1.6.2-R0.1-20130804.014923-14.jar -DgroupId=org.bukkit -DartifactId=bukkit -Dversion=1.6.2-R0.1-SNAPSHOT -Dpackaging=jar -DgeneratePom=true

mvn clean install
