config-version: 19

database-support: false

database:
  username: us3r
  isolation: SERIALIZABLE
  driver: org.sqlite.JDBC
  password: passw0rd
  url: jdbc:sqlite:plugins/zPermissions/zPermissions.db

database-read-only: false

group-permission: 'group.%s'

assigned-group-permission: ''

assigned-groups-can-include-default: true

default-group: default

explicit-default-group-membership: false

default-track: default

dump-directory: zPermissions-dumps

default-temp-permission-timeout: 60

tracks:
  default:
  - default
  - somegroup
  - someothergroup

default-primary-group-track: ''

kick-on-error: true

kick-ops-on-error: false

auto-refresh-interval: -1

auto-refresh-force: false

opaque-inheritance: true

interleaved-player-permissions: true

rank-admin-broadcast: false

inherited-metadata: false

native-vault-bridges: true

vault-prefix-includes-group: true

vault-metadata-includes-group: true

vault-group-test-uses-assigned-only: false

vault-get-groups-uses-assigned-only: false

vault-player-prefix-format: ''

vault-player-suffix-format: ''

log-vault-changes: false

debug: false
